README.md

Now that rubyforge is dead, we should replace its URL for the GitHub one.

Change Rack::Request URL in the README

---

lib/rack/attack/store_proxy/redis_store_proxy.rb
spec/integration/rack_attack_cache_spec.rb

Delete the key outright to support #113

Support delete method for Redis

---

lib/rack/attack/cache.rb
lib/rack/attack/fail2ban.rb
spec/fail2ban_spec.rb
spec/integration/rack_attack_cache_spec.rb

This code is in production as a monkey-patch in GitLab v7.10, and I thought it would be helpful for others.
Closes #113

Provide the ability to reset Fail2Ban count and ban flag

---

README.md

I see it has been closed, but I also got tripped up by #132.  I'd like to add a note to the README to avoid confusion.

Add note to README.md about scoping of Fail2Ban filters

---

Gemfile
Guardfile
spec/spec_helper.rb

Allows running tests with `bundle exec guard`.
Also use `pry` instead of `debugger`.

Development testing improvements with guard and pry

---

Appraisals
gemfiles/activesupport3.2.gemfile
gemfiles/activesupport4.0.gemfile
gemfiles/activesupport4.1.gemfile
gemfiles/activesupport4.2.gemfile
gemfiles/dalli1.1.gemfile
gemfiles/dalli2.gemfile

The gemfiles had drifted from the Appraisals file from which they’re
generated.

Fix Appraisals & gemfile tests

---

CHANGELOG.md
lib/rack/attack/store_proxy.rb
lib/rack/attack/version.rb

In v4.4.0, checking `defined?(ActiveSupport::Cache::MemCacheStore)`
could trigger an error loading dalli, which isn’t needed.
This fixes that bug, and prevents similar bugs by checking
`store.class.to_s` rather than `defined?(klass) && store.is_a?(klass)`.
Writing an automated test to ensure that dalli is truly optional is
difficult, but I was able to recreate the dalli load error in v4.4.0 by
running:
```bash
gem uninstall dalli
ruby -Ilib -ractive_support/all -ractive_support/cache/redis_store -rrack/attack -e 'p Rack::Attack::StoreProxy.build(Redis::Store.new)'
```
Fixes #163

Refactor StoreProxy to avoid autoloading MemCacheStore

---

.gitignore
CHANGELOG.md
README.md
examples/rack_attack.rb
lib/rack/attack.rb
lib/rack/attack/blocklist.rb
lib/rack/attack/fail2ban.rb
lib/rack/attack/request.rb
lib/rack/attack/safelist.rb
spec/allow2ban_spec.rb
spec/fail2ban_spec.rb
spec/rack_attack_request_spec.rb
spec/rack_attack_spec.rb

Hello! 
At Travis CI we've decided to change our usage of Whitelist/Blacklist to the less racially charged language of Safelist/Blocklist. We are using rack-attack and would love to use an updated version with our language choices if you are open to this change. I'm not sure how you would like to change the versioning of this so I didn't add any changes there. I know this would require users to update all of their whitelist/blacklist method calls to the new verbiage, which might annoy a number of end users. However, we did this with a simple find and replace (and method aliases until this change is welcomed). I added the depreciation warnings for the old method names to help users, however if anyone is relying on the rack.attack.match_type I changed it to safelist/blocklist (wasn't sure …

Controversial Language Change Suggestion

---

.travis.yml

It’s EOL, so we’re not supporting it anymore.

Drop tests for ruby 2.0.

---

spec/integration/offline_spec.rb

This fixes the error:
uninitialized constant ActiveSupport::VERSION
when loading active_support/cache/redis_store

[tests] Fix gotcha with new activesupport redis versions

---

spec/rack_attack_throttle_spec.rb

It's implied but not obvious that returning falsy from a `throttle` block means that the request does not match and will be disregarded. Added a spec to illustrate this explicitly.

add a spec to specify the behavior of non-matching throttle blocks

---

README.md

This addresses a use case from #191 of wanting to return rate limit information (especially `X-RateLimit-Reset`) for well-behaved clients.
Related: #29

README: add example for returning X-RateLimit-* headers

---

lib/rack/attack.rb
lib/rack/attack/version.rb

Fixes #197.
NB: `safelisted?` and `blocklisted?` should be considered unstable Rack::Attack api methods.

Fix args to deprecated methods

---

.travis.yml

Hi, this PR only bumps the JRuby to latest released stable.

Travis: use JRuby latest stable 9.1.7.0

---

README.md

This trivial PR makes the badges look cooler and shinier in the README.

README: Badges as SVG not PNG

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.

Travis: use jruby-9.1.10.0

---

.travis.yml

This PR updates the CI matrix to use latest JRuby.
http://jruby.org/2017/06/15/jruby-9-1-12-0.html

Travis: use latest jruby-9.1.12.0

---

README.md
examples/rack_attack.rb

So that gem users don't get the old hash syntax when copy-pasting examples into their app code.

Update docs to use new ruby hash syntax

---

.travis.yml
Appraisals
gemfiles/dalli2.gemfile
gemfiles/rails_4_2.gemfile
gemfiles/rails_5_0.gemfile
gemfiles/rails_5_1.gemfile

This PR updates both appraisal and travis configs to run tests (locally or in CI) against only the actively maintained ruby, rails and dalli versions.
Reference links:
* https://www.ruby-lang.org/en/downloads/branches://www.ruby-lang.org/en/downloads/branches/
* http://guides.rubyonrails.org/maintenance_policy.html
* https://www.ruby-lang.org/en/downloads/releases/

Only test against actively supported rubies and gems

---

spec/rack_attack_spec.rb

Exact same requests are in the `before` block in both cases.

Remove request duplication in rack_attack_spec.rb

---

README.md

So that users pasting these examples don't get
```
undefined method `seconds' for 5:Integer
```
if they're not using activesupport in their apps

Don't make README examples depend on activesupport

---

README.md

Thanks for your work on this gem! I have a small change to propose to the README. I was looking to return the cache key in a throttle response, and noticed that the `rack.attack.match_discriminator` environment key provides this. Thought it would be useful to mention as another example of what you can return in a throttle response.

Mention 'match_discriminator' in README.md

---

README.md

- use snake_case for initializer file name.
- surpress rubocop complains that use snake case for initializer file name.
README.md
config/initalizers/rack-attack.rb is recommended in README.md
[RuboCop complains about initializer file name · Issue #275 · kickstarter/rack-attack](https://github.com/kickstarter/rack-attack/issues/275)

fix rubocop complains about initializer file name (use snake_case)

---

Rakefile
rack-attack.gemspec
spec/acceptance/blocking_spec.rb
spec/acceptance/safelisting_spec.rb
spec/acceptance/throttling_spec.rb

Thought it might be a good idea to start a directory with tests which only focus is asserting what user expectations are about the gem public API/contract, without any assertions about internals.
These are very basic yet.
More to come if there's agreement it's a good idea :-)

Adds acceptance-oriented tests

---

lib/rack/attack/store_proxy/redis_store_proxy.rb

Fixes #253 
Found that `defined?` is buggy in ruby 2.5.0, which under certain circumstances users using rack-attack can hit (see [minimal app to reproduce issue 253](https://github.com/grzuy/ruby_app_for_rack_attack_253)).
I already reported (https://bugs.ruby-lang.org/issues/14407) and fixed (https://github.com/ruby/ruby/pull/1800) the underlaying issue in ruby, but i am guessing it's going to take some time before there's a new ruby release including the fix.
So for now, we would need to circumvent this ruby 2.5.0 bug by using `Object#const_defined?` instead of `defined?`, at least for this particular case.
---
__More details__:
Anyone using:
* ruby 2.5.0
* redis
* rack-attack without redis-store and using at least one throttle
* having a toplevel class named Store
will hit this ruby …

[Fixes #253] Avoid 'defined?' buggy behavior in ruby 2.5.0

---

lib/rack/attack.rb
lib/rack/attack/cache.rb
spec/rack_attack_store_config_spec.rb
spec/spec_helper.rb

Raises more semantic errors instead of blowing up with
```
undefined method `increment' for nil:NilClass
```

Help users understand more clearly when the store is misconfigured

---

spec/acceptance/track_spec.rb
spec/acceptance/track_throttle_spec.rb

Acceptance test Rack::Attack#track

---

spec/acceptance/fail2ban_spec.rb

Acceptance test fail2ban

---

.travis.yml
spec/acceptance/cache_store_config_for_allow2ban_spec.rb
spec/acceptance/cache_store_config_for_fail2ban_spec.rb

Acceptance test store config for allow2ban/fail2ban

---

lib/rack/attack.rb

`Rack::Attack::PathNormalizer` and `Rack::Attack::Request` are both
used in #call method, which is going to be used by every rack-attack
user as long as they insert the middleware in their app.

Don't autoload when it's barely valuable to do so

---

lib/rack/attack/store_proxy/redis_store_proxy.rb

[The bug leading to this code](https://bugs.ruby-lang.org/issues/14407) appears to be fixed.

Replace `const_defined?` with `defined?`

---

lib/rack/attack.rb
spec/spec_helper.rb

Avoid confusion like in https://github.com/kickstarter/rack-attack/issues/208#issue-190251995

Avoid user confusion by renaming .clear! to .clear_configuration

---

Rakefile

__Before__:
```
$ bundle exec rake test
Run options: --seed 27993
......................................................................
Fabulous run in 0.081738s, 856.3938 runs/s, 1052.1409 assertions/s.
70 runs, 86 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 51733
Fabulous run in 0.000513s, 0.0000 runs/s, 0.0000 assertions/s.
0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
Run options: --seed 12241
...................................................................
Fabulous run in 2.155369s, 31.0852 runs/s, 82.1205 assertions/s.
67 runs, 177 assertions, 0 failures, 0 errors, 0 skips
```
__After__:
```
$ bundle exec rake test
Run options: --seed 7980
...................................................................................................................... …
```

Make test run output a bit more clear by collapsing runs

---

README.md
lib/rack/attack.rb
spec/acceptance/track_spec.rb
spec/acceptance/track_throttle_spec.rb
spec/rack_attack_instrumentation_spec.rb

https://github.com/kickstarter/rack-attack/issues/255
Change the object type from instances of type Rack::Attack::Request to
instances of type Hash. (`req` becomes `:request => req`).
Fixes: #255

[Fixes #255] Change object type yielded to ActiveSupport::Subscribers

---

README.md
lib/rack/attack/cache.rb
lib/rack/attack/throttle.rb
spec/rack_attack_throttle_spec.rb

Aiming to solve https://github.com/kickstarter/rack-attack/issues/283
Add an reader for the epoch_time variable in the cache so that it can also be returned in the data from the throttle.
This is allows access to the same time that the cache uses for the count. This can be important for clients that want to provide rate limit information for well-behaved clients

[Fixes #283] Provide epoch_time that was used for the request in the data set

---

lib/rack/attack.rb
lib/rack/attack/store_proxy.rb
lib/rack/attack/store_proxy/redis_proxy.rb
spec/integration/rack_attack_cache_spec.rb

While a cache-store proxy exists for the redis-store gem, no such proxy existed for using the redis gem itself. This fills that gap by adding such a proxy.
Resolves kickstarter/rack-attack#190

[Fixes #213] Add support for the redis gem

---

.travis.yml

I am starting to find it difficult to argue in favor of having jruby in
the list of TravisCI rubies.
It adds a bit of extra cost in maintenance and time spent waiting build to finish,
without feeling we're getting a lot out of it. Thus, the feeling is that it has low ROI.
Reasons behind my feeling of not "getting a lot out of it" includes:
- Almost never coming across a situation in which I thought to myself
"Hey, with this change we're making the gem incompatible with jRuby" because most
of the failures on jRuby builds where either heisenbugs and/or rvm installation
problems with jRuby, at least in my experience
- Usage share seems to be very very low, even compared to unmaintained
MRI versions, according to some sources, e.g.
https://semaphoreci.com/blog/2017/11/08/ruby-versions-used-in- …

Stop running TravisCI against jRuby for now

---

README.md

The IETF decided the X- style custom headers have caused more headache than the value: https://tools.ietf.org/html/rfc6648 so this tool (which is very popular and much loved) shouldn't suggest using an old style.

Prefer to not use X- style headers for clarity

---

lib/rack/attack.rb
lib/rack/attack/store_proxy.rb
lib/rack/attack/store_proxy/mem_cache_store_proxy.rb
spec/acceptance/stores/active_support_mem_cache_store_pooled_spec.rb
spec/acceptance/stores/active_support_mem_cache_store_spec.rb

We recently added `pool_size` to our Rails cache options:
```
config.cache_store = :mem_cache_store, *memcache_hosts, pool_size: 5
```
and discovered that Rack::Attack was no longer throttling.  (StoreProxy.build wasn't detecting the store as proxyable, so would return the bare ActiveSupport::Cache::MemCacheStore instance rather than a DalliProxy)
This PR refactors the ConnectionPool handling into a PoolProxy superclass, and makes StoreProxy.build aware of ConnectionPools.
WDYT?

Fix usage with connection-pooled MemCacheStore

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb

`raw: true` isn't doing anything special for `read`, only for `write`

Remove unnecessary wrapping of ActiveSupport::Cache::RedisCacheStore#read

---

lib/rack/attack.rb
lib/rack/attack/store_proxy.rb
lib/rack/attack/store_proxy/active_support_redis_store_proxy.rb
spec/acceptance/stores/active_support_redis_store_spec.rb

Complete the process of moving away from "unwrapping store classes".
The rationale behind is we don't want to depend on any internals of externally developed cache store. We only wrap/proxy/adapt to the public interface using delegation.
Related comments in previous issues:
- https://github.com/kickstarter/rack-attack/pull/374#discussion_r214226206
- https://github.com/kickstarter/rack-attack/pull/374#issuecomment-417870761

Remove store class unwrapping completely

---

docs/advanced_configuration.md

Instead of matching the URL with complex regex, it can be much easier to mach specific controller actions.

Add example: Match Actions in Rails

---

.rubocop.yml
lib/rack/attack.rb
lib/rack/attack/blocklist.rb
lib/rack/attack/check.rb
lib/rack/attack/safelist.rb
lib/rack/attack/store_proxy/dalli_proxy.rb
lib/rack/attack/store_proxy/redis_proxy.rb
lib/rack/attack/store_proxy/redis_store_proxy.rb
lib/rack/attack/throttle.rb
lib/rack/attack/track.rb
rack-attack.gemspec
spec/acceptance/cache_store_config_for_allow2ban_spec.rb
spec/acceptance/cache_store_config_for_fail2ban_spec.rb
spec/spec_helper.rb

Continue what started in https://github.com/kickstarter/rack-attack/pull/330 and https://github.com/kickstarter/rack-attack/pull/338

Code style updates

---

README.md

#405 changed the subscription syntax to comply with `ActiveSupport` specification.
This Pull Request updates an example in the README that used the old syntax.

Update README example with new ActiveSupport Notification syntax

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb

RedisCacheStoreProxy will blow up when RedisCacheStore raises a
CommandError exception. In fact, by default the proxied store only
handles BaseConnectionError exceptions, but will let bubble up any other
type of exception from the underlying client.
This pull request uses the same approach from RedisProxy, where store
operations are wrapped in a `rescuing` block that rescues and ignores
BaseError exceptions (the most generic exception class that can be
raised by the Redis client).
Best viewed [ignoring whitespaces](https://github.com/kickstarter/rack-attack/pull/421/files?w=1).

Failsafe on Redis error replies in RedisCacheStoreProxy.

---

lib/rack/attack/store_proxy/redis_proxy.rb
spec/integration/offline_spec.rb

Fix rescuing errors in RedisProxy#increment

---

lib/rack/attack.rb
lib/rack/attack/configuration.rb

Extract Configuration class

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb
lib/rack/attack/store_proxy/redis_proxy.rb
spec/integration/offline_spec.rb

It is a very bad idea to rescue **all** redis errors (including errors for invalid commands). We can't know when we messed things up in code, because all errors will be silently swallowed. It is better to rescue only connection-related errors. `RedisCacheStore` already rescues connection errors, so no need to do it manually.

Do not rescue all errors for redis backed stores

---

lib/rack/attack.rb
lib/rack/attack/throttle.rb
spec/rack_attack_throttle_spec.rb

Closes #395 
I think, as also mentioned in original issue, discriminators should not only be `downcase`d, but also `strip`ed and `chomp`ed to avoid fooling counters by adding whitespaces.
I'm open for better name to `case_insensitive_discriminator` setting.

Make discriminators case-insensitive by default

---

lib/rack/attack.rb
lib/rack/attack/cache.rb
lib/rack/attack/store_proxy/redis_proxy.rb
spec/rack_attack_spec.rb

https://github.com/kickstarter/rack-attack/issues/249#issuecomment-539029878
I can think of 2 (not functionally equal) implementations:
1. `Rack::Attack.reset!` which really resets (deletes) specific keys in cache store and can be used for testing as well as production. But, while this can be implemented for most of cache stores (using https://api.rubyonrails.org/classes/ActiveSupport/Cache/Store.html#method-i-delete_matched), this is not (and can't be) supported by memcache (the second most popular cache store), because to reset state, we should know exact key names, which is impossible for production considering rack-attack's dynamic key names nature. Unfortunately, memcache does not support deleting based on patterns/prefixes, like in redis. And need to figure out how to use this with …

Allow to reset state

---

.rubocop.yml
.travis.yml
rack-attack.gemspec

https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/

Remove support for ruby 2.3

---

lib/rack/attack.rb
lib/rack/attack/railtie.rb
spec/acceptance/rails_middleware_spec.rb
spec/spec_helper.rb

Because of the sort algorithm rails uses to satisfy `after` and `before`
constraints, gems can have unintended effects on others. See
https://github.com/rails/rails/commit/0a120a818d413c64ff9867125f0b03788fc306f8
Prefer making rack-attack middleware idempotent instead of relying on
the load order and the contents of the middleware stack too much.
closes #452
closes #456

fix: avoid unintended effects on load_config_initializers and other gems load order

---

README.md
docs/development.md
lib/rack/attack.rb
lib/rack/attack/configuration.rb
spec/acceptance/customizing_blocked_response_spec.rb
spec/acceptance/customizing_throttled_response_spec.rb
spec/rack_attack_spec.rb

Hello, I would like to propose an improvement that our company uses internally as a monkey-patch, to which I've added the tests, backward compatibility and proper styling for community use.
In short, when a request is throttled or blocklisted, it's much more convenient to have access to a complete Rack request object instead of just environment hash - for example, for the reporting purposes.
This request contains the following:
1. Adds new variables for the callbacks with better naming, which now receive Rack request instead of an environment object.
2. It retains backward compatibility with the previous implementation.
3. Updates to documentation to match the proposed interface.
4. Small improvement for development docs.
Please let me know what you think.

Feature proposal: Request instead of Env in callbacks

---

README.md

The README currently has two sections titled "Testing", with the same anchor (so clicking on the second "Testing" link in the Table of Contents actually links to the first "Testing" section). This PR consolidates the two sections into a single section.

Consolidate #testing section of README

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb

Rails 5.2.4.3 was released today, with a [security fix](https://github.com/rails/rails/commit/467e3399c9007996c03ffe3212689d48dd25ae99) for [CVE-2020-8165](https://groups.google.com/forum/#!topic/rubyonrails-security/bv6fW4S0Y1c). As a result of this fix, Rack::Attack now throws deprecation warnings, because it writes a value to cache with `raw: true` but reads it back in a subsequent request WITHOUT `raw: true`.

Fix deprecation warning in Rails 5.2.4.3

---

.rubocop.yml
lib/rack/attack/cache.rb
lib/rack/attack/check.rb
lib/rack/attack/throttle.rb
rack-attack.gemspec

This PR updates RuboCop to latest release.
- enable each of the new Cops
- mark each new Cop with the version they appeared in
- use RuboCop with `-a` for autofix
[RuboCop 0.84.0 release notes](https://github.com/rubocop-hq/rubocop/releases/tag/v0.84.0)
---
I saw that this repo was using a slightly outdated RuboCop when running the tests for https://github.com/rack/rack/pull/1664

Use RuboCop 0.84.0

---

README.md

In trying to track down a bug here turns out I was trying to reference the wrong header shown in the readme. 
Printing our `request.env` it becomes clear this is just the full request object:
```
{"rack.version"=>[1, 3],
"rack.errors"=>#<IO:<STDERR>>,
"rack.multithread"=>true,
"rack.multiprocess"=>false,
"rack.run_once"=>false,
"SCRIPT_NAME"=>"",
"QUERY_STRING"=>"",
"SERVER_PROTOCOL"=>"HTTP/1.1",
"SERVER_SOFTWARE"=>"puma 4.3.5 Mysterious Traveller",
"GATEWAY_INTERFACE"=>"CGI/1.2",
"REQUEST_METHOD"=>"POST",
"REQUEST_PATH"=>"/api/v1/....",
"REQUEST_URI"=>"/api/v1/...",
"HTTP_VERSION"=>"HTTP/1.1",
"HTTP_HOST"=>"example.com",
"HTTP_APIKEY"=>"secret_key",
"CONTENT_TYPE"=>"application/json",
"HTTP_USER_AGENT"=>"PostmanRuntime/7.25.0",
"HTTP_ACCEPT"=>"*/*",
"HTTP_CACHE_CONTROL"=>"no-cache",
... …
```

Clarify Calling HTTP_APIKey header in example

---

README.md
docs/example_configuration.md
examples/rack_attack.rb

This commit mitigates rate limit bypasses in the configuration
docs by normalizing the email throttle key. (The normalization process
used is the same as used by the Clearance gem.)
---
Often an authentication process normalizes email addresses and usernames
before look up, say by downcasing and removing any whitespace.
Throttles that do not perform the same normalization are vulnerable
to rate limit bypasses.
For example, an attacker can bypass a vulnerable throttle by using
unlimited case and whitespace variants for the same email address:
- Variant 1: `victim@example.org`
- Variant 2: `victim@example. org`
- Variant 3: `victim@example . org`
- Variant 4: `ViCtIm@eXaMpLe.org`
- etc, etc.
All of these variants resolve to the same email address, but allow
an attacker to bypass a …

Mitigate login throttle bypasses in docs

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb

fix https://github.com/rack/rack-attack/issues/508

Fix Ruby 2.7 kwargs warning in RedisCacheStoreProxy

---

docs/example_configuration.md

This updates the `logins/email` config to use single quotes, for consistency with the other examples in the example config.

Use single quotes in example configuration

---

README.md

The link for the Rack app interface was broken.
Updated the link so it now resolves to the intended documentation.

docs: update link to rack spec in README

---

rack-attack.gemspec

Hi 👋 
Including the LICENSE in gem builds is helpful when generating a report including licenses from all your dependencies.
`rack/rack` [does it](https://github.com/rack/rack/blob/c1e5fbbb59101c039e8b657c8052e152c572d5ac/rack.gemspec#L20-L21) for instance.

Include LICENSE in gem build

---

lib/rack/attack/store_proxy/redis_proxy.rb

Redis 4.6.0 deprecated calling commands on `Redis` inside `#pipelined`:
redis.pipelined do
redis.get("key")
end
The above should be:
redis.pipelined do |pipeline|
pipeline.get("key")
end
See: https://github.com/redis/redis-rb/pull/1059

fix: Fix redis-rb 4.6.0 deprecation warnings

---

lib/rack/attack/cache.rb
lib/rack/attack/path_normalizer.rb

Hi,
git.io URL has been deprecated, and it will stop redirecting on April 29, 2022.
For more detail:
https://github.blog/changelog/2022-04-25-git-io-deprecation/

Replace git.io URL

---

README.md

This was part of the "lessons learned" from Bannerbear's DDoS attack: https://www.bannerbear.com/blog/how-to-survive-a-ddos-attack/
I think perhaps many people are blindly copying this line from the readme:
```ruby 
Rack::Attack.cache.store = ActiveSupport::Cache::MemoryStore.new # defaults to Rails.cache
```
There really isn't a reason to have this line in the Readme, because the default is OK. We should include an example of what most apps will probably want to do, which is to set this to a Redis or Memcached store, not a MemoryStore, which is probably appropriate only for local-only toy apps.

Add note about cache stores and in-memory caches.

---

spec/spec_helper.rb

The latest version of minitest dropped the [ancient MiniTest compatibility layer][1], so we need to use the newer module name, `Minitest`.
[1]: https://github.com/minitest/minitest/blob/master/History.rdoc#label-5.19.0+-2F+2023-07-26

Rename MiniTest -> Minitest

---

CHANGELOG.md

Content of `CHANGELOG.md` based on https://github.com/rack/rack-attack/releases/tag/v6.7.0.
A possible alternative would be to change this line at the top of `CHANGELOG.md`:
> All notable changes to this project will be documented in this file.
To something like:
> All changes after v6.6.1 will be documented in the relevant release note.
Addresses #616.

Update changelog for v6.7.0

---

CHANGELOG.md

* Add missing reference to `CHANGELOG.md` for v6.7.0.
* Explain that `CHANGELOG.md` will no longer be updated.

Changelog changes

---

.github/workflows/build.yml

Adds Ruby 3.2.2 to GitHub Actions and bumps older Rubies to latest patch levels.

Add Ruby 3.2.2 to CI build matrix, update older Rubies

---

lib/rack/attack/configuration.rb
spec/acceptance/blocking_ip_spec.rb
spec/acceptance/safelisting_ip_spec.rb

From https://github.com/rack/rack-attack/issues/588 we can see that if for some reason the `request.ip` is missing, `rack-attack` will try to do `IPAddr.new(nil)` which raises `*** IPAddr::AddressFamilyError Exception: address family must be specified`.
With this PR we only call IPAddr.new if we have a not empty string

Fix #588 don't fail if request.ip is missing

---

.github/workflows/build.yml
Appraisals
gemfiles/active_support_5_redis_cache_store.gemfile
gemfiles/active_support_5_redis_cache_store_pooled.gemfile
gemfiles/active_support_redis_cache_store.gemfile
gemfiles/active_support_redis_cache_store_pooled.gemfile
gemfiles/connection_pool_dalli.gemfile
gemfiles/dalli2.gemfile
gemfiles/dalli3.gemfile
gemfiles/rack_1.gemfile
gemfiles/rack_2.gemfile
gemfiles/rack_3.gemfile
gemfiles/rails_4_2.gemfile
gemfiles/rails_6_0.gemfile
gemfiles/rails_6_1.gemfile
gemfiles/rails_7_0.gemfile
gemfiles/rails_7_1.gemfile
gemfiles/redis_4.gemfile
gemfiles/redis_5.gemfile
gemfiles/redis_store.gemfile

Add gemfile to prevent regressions in ActiveSupport 5 which is actively supported by `rack-attack`
Note:
- Changes in other gemfiles were done by Appraisals

ci: test against ActiveSupport::RedisCacheStore v5

---

.github/workflows/build.yml

With this change we don't need to care about patch versions
Note: I'm using strings as suggested in https://github.com/ruby/setup-ruby#supported-version-syntax. If you don't use the commas, most versions just work but `3.0` fails for some strange reason

ci: automatically run with latest ruby patch version

---

lib/rack/attack/throttle.rb

This is a very minor refactor, but I think worth it given that it was the source of confusion here https://github.com/rack/rack-attack/pull/578/files#r1374864157.

Minor refactoring

---

lib/rack/attack/store_proxy/redis_cache_store_proxy.rb

As far as I can tell, Rails has handled increment+expires_in since
6.0 (https://github.com/rails/rails/commit/9d5b02ec5062a23665ec596ef7d3efe4f5abcc27), and more recent versions add pipeline optimizations on top of that.
How about avoiding our own custom RedisCacheStoreProxy#increment method on modern versions of ActiveSupport?
This also avoids an extra GET (from the `if options[:expires_in] && !read(name)` call).

Avoid RedisCacheStore#increment on Rails 6+

---

spec/rack_attack_throttle_spec.rb

Noticed a CI failure here - https://github.com/rack/rack-attack/actions/runs/6932050109/job/18855154765 - which I think is due to the system clock rolling over 15:14:00 while mid-test. How about freezing time in these specs?

Freeze time to fix flakey specs

---

.github/workflows/build.yml

Fix the following warning in the CI:
>The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

ci: Update checkout action

---

spec/acceptance/stores/active_support_dalli_store_spec.rb
spec/acceptance/stores/active_support_mem_cache_store_pooled_spec.rb
spec/acceptance/stores/active_support_mem_cache_store_spec.rb
spec/acceptance/stores/active_support_memory_store_spec.rb
spec/acceptance/stores/active_support_redis_cache_store_pooled_spec.rb
spec/acceptance/stores/active_support_redis_cache_store_spec.rb
spec/acceptance/stores/connection_pool_dalli_client_spec.rb
spec/acceptance/stores/dalli_client_spec.rb
spec/acceptance/stores/redis_spec.rb
spec/acceptance/stores/redis_store_spec.rb
spec/rack_attack_throttle_spec.rb
spec/support/cache_store_helper.rb
spec/support/freeze_time_helper.rb

Example of failure https://github.com/santib/rack-attack/actions/runs/7199119786/job/19610109965
```
........F
Failure:
ActiveSupport::Cache::MemoryStore as a cache backend#test_0002_works for fail2ban [/home/runner/work/rack-attack/rack-attack/spec/support/cache_store_helper.rb:36]:
Expected: 403
Actual: 200
bin/rails test /home/runner/work/rack-attack/rack-attack/spec/support/cache_store_helper.rb:19
..........................................................................S....................................................................
Finished in 2.172762s, 69.9571 runs/s, 132.5502 assertions/s.
[15](https://github.com/santib/rack-attack/actions/runs/7199119786/job/19610109965#step:5:16)2 runs, 288 assertions, 1 failures, 0 errors, 1 skips
```

ci: freeze time in more specs

---

.github/workflows/build.yml

There is no reason why we want to fail fast on the CI.
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast

ci: Don't fail fast

---

README.md

[ActiveSupport::Notifications.subscribe](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html#method-c-subscribe)'s block arguments are as follows (taken from the Rails API docs):
```ruby
ActiveSupport::Notifications.subscribe('render') do |name, start, finish, id, payload|
name    # => String, name of the event (such as 'render' from above)
start   # => Time, when the instrumented block started execution
finish  # => Time, when the instrumented block ended execution
id      # => String, unique ID for the instrumenter that fired the event
payload # => Hash, the payload
end
```
The README makes it look like the `id` argument would be the request ID, which is not the case.

Fix AS::Notification.subscribe arguments in README.md

---

spec/acceptance/blocking_ip_spec.rb
spec/acceptance/blocking_spec.rb
spec/acceptance/blocking_subnet_spec.rb
spec/acceptance/safelisting_ip_spec.rb
spec/acceptance/safelisting_spec.rb
spec/acceptance/safelisting_subnet_spec.rb
spec/acceptance/throttling_spec.rb
spec/acceptance/track_spec.rb
spec/acceptance/track_throttle_spec.rb
spec/rack_attack_track_spec.rb

- Unify how notifications are tracked and checked using `Array`'s `#push` `#pop` and `#size`.
- With this now we not only check "some notification happened" but the exact amount of notifications since in some cases we might trigger more than once, so this can prevent missing or mixing notifications.
Note: We could introduce a custom class built on top of Array with some facilities but seems to not be worth it at the time

Refactor notifications checks in tests

---

spec/acceptance/fail2ban_spec.rb

In https://github.com/rack/rack-attack/pull/655 there is work in progress to instrument when a request gets banned.
This PR adds a test just to make sure that we don't introduce a breaking change without notice.
In PR #655 we need to pass the `request` to `Fail2Ban` and this test fails.

Add test to prevent regressions

---

lib/rack/attack/configuration.rb
spec/configuration_spec.rb

**Description**:
This pull request adds the missing `tracks` attribute reader to the `Rack::Attack::Configuration` class. This change ensures that the `tracks` attribute is accessible, consistent with other attributes such as `safelists`, `blocklists`, and `throttles`.
**How this was discovered?**
```
> Rack::Attack.tracks.clear
=> warning: #<Class:Rack::Attack>#tracks at /.rbenv/versions/3.1.3/lib/ruby/3.1.0/forwardable.rb:157 forwarding to private method Rack::Attack::Configuration#tracks
/.rbenv/versions/3.1.3/lib/ruby/3.1.0/forwardable.rb:236:in `tracks': undefined method `tracks' for #<Rack::Attack::Configuration:0x000000010c09e978...
```
**Changes**:
- Added `:tracks` to the `attr_reader` in `lib/rack/attack/configuration.rb`.
- Updated `spec/configuration_spec.rb` to include tests …

[BUG] Add tracks attr_reader to Configuration

---

.github/workflows/build.yml

Follows-up https://github.com/rack/rack-attack/pull/679 to fix the CI, given that I left it in an incorrect state after a failed merge resolution 😅

Fix wrong merge resolution

---

README.md

CodeClimate doesn't exist anymore. We may want to consider to install qlty.sh which is the successor of CodeClimate.
https://qlty.sh/gh/rack/projects/rack-attack

Remove CodeClimate

---

.github/workflows/build.yml

https://github.com/actions/runner-images/issues/11101
Ubuntu 20.04 is not available anymore

Fix GHA Runner
