rack/rack-attack

- CODE_OF_CONDUCT.md
I added some headings, emoji, and made assorted copy tweaks to more closely match the project's documentation writing style. This is a follow-up to PR #134.
(The differences are easiest to see with the rich-diff view)
> Update code of conduct for tone

- README.md
> README: add ipv6 example

- gemfiles/activesupport4.1.gemfile
- gemfiles/activesupport4.2.gemfile
- gemfiles/dalli2.gemfile
...since I stopped testing it in #184
> Remove ruby2.0 exceptions from gemfiles

- README.md
Hey
Added documentation on requirements needed to run test suite (Redis and Memcached) under _"Contributing"_ heading.
> added discussion about how to run test suite

- lib/rack/attack/allow2ban.rb
This is just a minor correction on a comment in the allow2ban file.
> Typo in comment

- spec/rack_attack_request_spec.rb
- spec/rack_attack_spec.rb
- spec/rack_attack_throttle_spec.rb
- spec/rack_attack_track_spec.rb
- spec/spec_helper.rb
Just trying to make it more obvious to someone reading the tests, that the method is making assertions in it's implementation. Wasn't clear to me the when i read it first time.
> Attempt to make it easier to understand that the method is making assertions

- spec/acceptance/customizing_blocked_response_spec.rb
- spec/acceptance/customizing_throttled_response_spec.rb
- spec/spec_helper.rb
> Acceptance test ability to customize blocked/throttled responses

- spec/acceptance/allow2ban_spec.rb
> Acceptance test allow2ban

- spec/acceptance/throttling_spec.rb
> Acceptance test throttle Retry-After header

- rack-attack.gemspec
- spec/acceptance/cache_store_config_with_rails_spec.rb
> Acceptance test cache store config when Rails is present

- spec/acceptance/throttling_spec.rb
> Acceptance test throttle dynamic arguments

- spec/acceptance/extending_request_object_spec.rb
> Acceptance test ability to extend the request object

- spec/acceptance/customizing_blocked_response_spec.rb
- spec/acceptance/customizing_throttled_response_spec.rb
> Acceptance test access to match data in custom responses

- CHANGELOG.md
- lib/rack/attack/cache.rb
- spec/acceptance/cache_store_config_for_allow2ban_spec.rb
- spec/acceptance/cache_store_config_for_fail2ban_spec.rb
> Give clearer error message for misconfigured cache store for allow/fail2ban

- spec/acceptance/blocking_spec.rb
- spec/acceptance/safelisting_spec.rb
- spec/acceptance/throttling_spec.rb
> Acceptance test ability to subscribe to notifications

- CHANGELOG.md
- lib/rack/attack.rb
- lib/rack/attack/check.rb
- spec/acceptance/blocking_ip_spec.rb
- spec/acceptance/blocking_subnet_spec.rb
- spec/acceptance/safelisting_ip_spec.rb
- spec/acceptance/safelisting_subnet_spec.rb
> Provide shorthands for block/safelisting IPs and subnets

- README.md
> [Fixes #318] Attempt to improve README a bit

- CONTRIBUTING.md
- README.md
- docs/development.md
> [Fixes #321] Provide some advice for users willing to contribute to the project

- .rubocop.yml
- Guardfile
- lib/rack/attack.rb
- lib/rack/attack/allow2ban.rb
- lib/rack/attack/blocklist.rb
- lib/rack/attack/cache.rb
- lib/rack/attack/check.rb
- lib/rack/attack/fail2ban.rb
- lib/rack/attack/path_normalizer.rb
- lib/rack/attack/safelist.rb
- lib/rack/attack/store_proxy.rb
- lib/rack/attack/store_proxy/dalli_proxy.rb
- lib/rack/attack/store_proxy/mem_cache_proxy.rb
- lib/rack/attack/store_proxy/redis_store_proxy.rb
- rack-attack.gemspec
- spec/acceptance/safelisting_ip_spec.rb
- spec/allow2ban_spec.rb
- spec/fail2ban_spec.rb
- spec/rack_attack_dalli_proxy_spec.rb
- spec/rack_attack_spec.rb
- spec/rack_attack_throttle_spec.rb
- spec/rack_attack_track_spec.rb
- spec/spec_helper.rb
As discussed in #302, this is the first step in adopting a style guide.
This PR will fix all layout offenses in both the lib and the specs. I'll also update the contribution guide to mention the guide and Rubocop.
Still a work in progress.
> [Fixes #302] Initial style guide adoption

- CONTRIBUTING.md
As a continuation of #330, this PR adds a small section regarding the Style guide in the `CONTRIBUTING` file.
> [Fixes #302] Add a section on Style Guide in the CONTRIBUTING file

- spec/acceptance/stores/mem_cache_store_spec.rb
- spec/acceptance/stores/redis_cache_store_spec.rb
- spec/support/cache_store_helper.rb
> Acceptance test use of ActiveSupport::Cache::MemCacheStore

- rack-attack.gemspec
Follow-up of https://github.com/kickstarter/rack-attack/pull/359
> Remove unused development dependency (memcache-client)

- lib/rack/attack.rb
- spec/rack_attack_spec.rb
> Remove previously deprecated public methods

- lib/rack/attack/cache.rb
- spec/acceptance/cache_store_config_for_allow2ban_spec.rb
- spec/acceptance/cache_store_config_for_fail2ban_spec.rb
Give more info in the exception message to help users self debug misconfigured stores, like in https://github.com/kickstarter/rack-attack/issues/391.
> feat: improve MisconfiguredStoreError exception message to aid debugging

- README.md
- examples/instrumentation.rb
- lib/rack/attack.rb
- spec/acceptance/blocking_ip_spec.rb
- spec/acceptance/blocking_spec.rb
- spec/acceptance/blocking_subnet_spec.rb
- spec/acceptance/safelisting_ip_spec.rb
- spec/acceptance/safelisting_spec.rb
- spec/acceptance/safelisting_subnet_spec.rb
- spec/acceptance/throttling_spec.rb
- spec/acceptance/track_spec.rb
- spec/acceptance/track_throttle_spec.rb
- spec/rack_attack_instrumentation_spec.rb
- spec/rack_attack_track_spec.rb
> Match ActiveSupport Instrumentation event name format spec

- lib/rack/attack.rb
- spec/acceptance/blocking_spec.rb
- spec/acceptance/safelisting_spec.rb
> Make blocklist/safelist name argument optional

- README.md
- lib/rack/attack/throttle.rb
- spec/rack_attack_throttle_spec.rb
> feat: provide discriminator in throttle_data

- .rubocop.yml
- lib/rack/attack.rb
- lib/rack/attack/cache.rb
- lib/rack/attack/check.rb
- lib/rack/attack/path_normalizer.rb
- lib/rack/attack/store_proxy/active_support_redis_store_proxy.rb
- lib/rack/attack/store_proxy/mem_cache_store_proxy.rb
- lib/rack/attack/throttle.rb
- lib/rack/attack/track.rb
- rack-attack.gemspec
- spec/acceptance/stores/active_support_mem_cache_store_pooled_spec.rb
- spec/acceptance/stores/active_support_redis_cache_store_pooled_spec.rb
- spec/acceptance/stores/active_support_redis_cache_store_spec.rb
- spec/acceptance/stores/connection_pool_dalli_client_spec.rb
- spec/rack_attack_spec.rb
> Enable more code style checks

- docs/advanced_configuration.md
> Single spelling correction

- lib/rack/attack/throttle.rb
Hopefully, if it fixes the #427, and sets the number of issues in Code Climate to 0 💪!
As @grzuy said in the mentioned issue, Code Climate complains about the complexity of this method. Here we try to reduce it by using private methods that encapsulate some details that are not required to understand the implementation of the main method.
> Refactor `Throttle#matched_by?` method

- README.md
- lib/rack/attack.rb
- lib/rack/attack/configuration.rb
- spec/acceptance/throttling_spec.rb
- spec/rack_attack_throttle_spec.rb
> Allow to configure Retry-After header for default throttled_response handler

- README.md
- lib/rack/attack/railtie.rb
- spec/acceptance/rails_middleware_spec.rb
> Auto include middleware for older railses

- README.md
Just reading through the Readme and this tripped me up a little. Small change to make this more inclusive.
> Use gender-neutral pronoun in Readme

- .github/workflows/build.yml
- Appraisals
- gemfiles/dalli3.gemfile
- spec/acceptance/stores/active_support_dalli_store_spec.rb
This adds testing support for dalli 3.0.
Precursor to #556.
> Test against dalli 3.0

- lib/rack/attack/configuration.rb
See https://github.com/rack/rack/pull/1812 for more details.
> Lower case headers.

- README.md
Hi Team,
First of all, thank you for your continued effort in maintaining this gem. It's appreciated.
This PR attempts to fix the documentation given recent config deprecation.
> fix(documentation): Updating README with non-deprecated configuration.
